use crate::common::exit_with_error;

fn main() {
    exit_with_error(err);
}
